### ISSUE TITLE
Twitch?

### ISSUE THREAD

**Issue by paulmaloney** [panzi/embedplayer#7]
Hey just been trying it all out and it works great! Only issue I've found is the twitch videos the controls play/pause/volume etc.. don't work?

**Comment by panzi** [comment]
Thanks for the report. Fixed it! It now requires the embedding website to pass `&origin=<embedding site's origin>` to the iframe.

**Comment by paulmaloney** [comment]
Perfect! Thansk so much, loving the player :D
